export const mutationPost = `
    createPost(
        language: String,
        commentStatus: String!
        status: Int!
        type: Int!
        isHot: Int!
        showTop: Int!
        categoryId: ID!
        topicId: ID!
        authorId: ID!
        name: String
        slugs: String!
        photo: String
        thumb: String
        photoData: String
        fileListen: String
        summary: String
        content: String
        title: String
        description: String
        tags: String
        source: String
        viewed: String
        viewTotal: Int
        viewDay: Int
        viewWeek: Int
        viewMonth: Int
        viewYear: Int
        note: String
        slideView: Boolean
        releaseTime: String
        outdatedAt: String
        ): Post,
        updateCategory(
        id: ID!,
        language: String
        commentStatus: String
        status: Int
        type: Int
        isHot: Int
        showTop: Int
        categoryId: ID
        topicId: ID
        authorId: ID
        name: String
        slugs: String
        photo: String
        thumb: String
        photoData: String
        fileListen: String
        summary: String
        content: String
        title: String
        description: String
        tags: String
        source: String
        viewed: String
        viewTotal: Int
        viewDay: Int
        viewWeek: Int
        viewMonth: Int
        viewYear: Int
        note: String
        slideView: Boolean
        releaseTime: String
        outdatedAt: String
        ): Post,
        deletePost(id: ID!): String
`